// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFE.Console.TransferMoneyExample.Infra;

#nullable disable

namespace WFE.Console.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230425054715_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WFE.Console.TransferMoneyExample.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e07ed267-a765-431c-a420-941fd5cf429f"),
                            AccountNumber = "1258823",
                            Balance = 200m,
                            Owner = "Gholi"
                        },
                        new
                        {
                            Id = new Guid("020df25b-d01b-4a3b-9c2e-d73a31f2d1dd"),
                            AccountNumber = "9852333",
                            Balance = 200m,
                            Owner = "Taghi"
                        },
                        new
                        {
                            Id = new Guid("1a09b61b-bfd1-44f6-adb9-bf2e17c2e6f1"),
                            AccountNumber = "5245688",
                            Balance = 200m,
                            Owner = "Kokab"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
