// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFE.Console.TransferMoneyExample.Infra;

#nullable disable

namespace WFE.Console.TransferMoneyExample.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WFE.Console.TransferMoneyExample.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1179372c-1ce0-4cc5-a2f3-35b0c69ae035"),
                            AccountNumber = "1258823",
                            Balance = 200m,
                            Owner = "Gholi"
                        },
                        new
                        {
                            Id = new Guid("8629049e-5bbc-4ac0-ba78-864baafe1f00"),
                            AccountNumber = "9852333",
                            Balance = 200m,
                            Owner = "Taghi"
                        },
                        new
                        {
                            Id = new Guid("5dbf28b7-5a55-48af-9682-240ceb0a090d"),
                            AccountNumber = "5245688",
                            Balance = 200m,
                            Owner = "Kokab"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
